-- MySQL Script generated by MySQL Workbench
-- Tue Oct 28 16:40:26 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema linguasbd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema linguasbd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `linguasbd` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `linguasbd` ;

-- -----------------------------------------------------
-- Table `linguasbd`.`auth_rule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `linguasbd`.`auth_rule` (
  `name` VARCHAR(64) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  `data` BLOB NULL DEFAULT NULL,
  `created_at` INT NULL DEFAULT NULL,
  `updated_at` INT NULL DEFAULT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `linguasbd`.`auth_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `linguasbd`.`auth_item` (
  `name` VARCHAR(64) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  `type` SMALLINT NOT NULL,
  `description` TEXT COLLATE 'utf8mb3_unicode_ci' NULL DEFAULT NULL,
  `rule_name` VARCHAR(64) COLLATE 'utf8mb3_unicode_ci' NULL DEFAULT NULL,
  `data` BLOB NULL DEFAULT NULL,
  `created_at` INT NULL DEFAULT NULL,
  `updated_at` INT NULL DEFAULT NULL,
  PRIMARY KEY (`name`),
  INDEX `rule_name` (`rule_name` ASC) VISIBLE,
  INDEX `idx-auth_item-type` (`type` ASC) VISIBLE,
  CONSTRAINT `auth_item_ibfk_1`
    FOREIGN KEY (`rule_name`)
    REFERENCES `linguasbd`.`auth_rule` (`name`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `linguasbd`.`auth_assignment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `linguasbd`.`auth_assignment` (
  `item_name` VARCHAR(64) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  `user_id` VARCHAR(64) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  `created_at` INT NULL DEFAULT NULL,
  PRIMARY KEY (`item_name`, `user_id`),
  INDEX `idx-auth_assignment-user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `auth_assignment_ibfk_1`
    FOREIGN KEY (`item_name`)
    REFERENCES `linguasbd`.`auth_item` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `linguasbd`.`auth_item_child`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `linguasbd`.`auth_item_child` (
  `parent` VARCHAR(64) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  `child` VARCHAR(64) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  PRIMARY KEY (`parent`, `child`),
  INDEX `child` (`child` ASC) VISIBLE,
  CONSTRAINT `auth_item_child_ibfk_1`
    FOREIGN KEY (`parent`)
    REFERENCES `linguasbd`.`auth_item` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `auth_item_child_ibfk_2`
    FOREIGN KEY (`child`)
    REFERENCES `linguasbd`.`auth_item` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `linguasbd`.`migration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `linguasbd`.`migration` (
  `version` VARCHAR(180) NOT NULL,
  `apply_time` INT NULL DEFAULT NULL,
  PRIMARY KEY (`version`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `linguasbd`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `linguasbd`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  `auth_key` VARCHAR(32) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  `password_hash` VARCHAR(255) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  `password_reset_token` VARCHAR(255) COLLATE 'utf8mb3_unicode_ci' NULL DEFAULT NULL,
  `email` VARCHAR(255) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  `status` SMALLINT NOT NULL DEFAULT '10',
  `created_at` INT NOT NULL,
  `updated_at` INT NOT NULL,
  `verification_token` VARCHAR(255) COLLATE 'utf8mb3_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  UNIQUE INDEX `password_reset_token` (`password_reset_token` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
